# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import io
import sys

import folium
from PyQt5 import QtWidgets, uic, QtCore
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets
from PyQt5.QtGui import QPixmap, QIcon


class MainWindow_Ui(object):
    def setupUi(self, MainWindow):
        pixmap=QPixmap('C:/Users/ilyass/Desktop/projet/6395463.png')

# Create the QIcon object from the QPixmap
        icon = QIcon(pixmap)

# Set the window icon
        MainWindow.setWindowIcon(icon)
        MainWindow.setObjectName("SHELL")
        MainWindow.resize(824, 593)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#main_body{\n"
"background-color:#Fff48e;\n"
"border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"padding:5px;\n"
"background-color:#ffca5e;\n"
"border-radius:20px;\n"
"}\n"
"#side_menu{\n"
"background-color:#fff7b0;\n"
"border-radius:20px;\n"
"}\n"
"#centralwidget{\n"
"background-color:#fff;\n"
"}\n"
"*{\n"
"border:none;\n"
"background-color:transparent;\n"
"color:#071e26;\n"
"}\n"
"#header{\n"
"background-color:#fff7b0;\n"
"border-radius:20px;\n"
"}\n"
"#frame_4{\n"
"background-color:#fff7b0;\n"
"border-radius:20px;\n"
"\n"
"}\n"
"QToolButton{\n"
"padding:5px;\n"
"background-color:#ffca5e;\n"
"border-radius:5px;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setMinimumSize(QtCore.QSize(0, 50))
        self.header.setMaximumSize(QtCore.QSize(16777215, 50))
        self.header.setStyleSheet("")
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.header)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton.setStyleSheet("font: 75 14pt \"Alef\";")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/ilyass/Desktop/projet/menu (2).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.horizontalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignLeft)
        self.frame_3 = QtWidgets.QFrame(self.header)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setStyleSheet("image: url(C:/Users/ilyass/Desktop/projet/SeekPng.com_shell-logo-png_1409787.png);\n"
"")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setStyleSheet("image: url(C:/Users/ilyass/Desktop/projet/shell-logo.svg);\n"
"")
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.header, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(801, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.main_body = QtWidgets.QFrame(self.frame_2)
        self.main_body.setGeometry(QtCore.QRect(52, 0, 751, 521))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body.sizePolicy().hasHeightForWidth())
        self.main_body.setSizePolicy(sizePolicy)
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.main_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("\n"
"image: url(C:/Users/ilyass/Desktop/projet/SeekPng.com_shell-logo-png_1409735.png);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 50, 521))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.toolButton = QtWidgets.QToolButton(self.frame_4)
 #       self.toolButton.setGeometry(QtCore.QRect(1, 30, 170, 40))
  #      self.toolButton.setStyleSheet("\n"
#"font: 75 12pt \"Alef\";")
 #       icon1 = QtGui.QIcon()
  #      icon1.addPixmap(QtGui.QPixmap("C:/Users/ilyass/Desktop/projet/clipboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
   #     self.toolButton.setIcon(icon1)
    #    self.toolButton.setIconSize(QtCore.QSize(50, 50))
     #   self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
      #  self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.frame_4)
        self.toolButton_2.setGeometry(QtCore.QRect(1, 105, 170, 40))
        self.toolButton_2.setStyleSheet("font: 75 12pt \"Alef\";")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/ilyass/Desktop/projet/map-pin.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon2)
        self.toolButton_2.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.frame_4)
        self.toolButton_3.setGeometry(QtCore.QRect(1, 180, 170, 40))
        self.toolButton_3.setStyleSheet("font: 75 12pt \"Alef\";")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/ilyass/Desktop/projet/map.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon3)
        self.toolButton_3.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(self.frame_4)
        self.toolButton_4.setGeometry(QtCore.QRect(1, 397, 170, 40))
        self.toolButton_4.setStyleSheet("font: 75 12pt \"Alef\";")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/ilyass/Desktop/projet/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon4)
        self.toolButton_4.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_4.setObjectName("toolButton_4")
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
      

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        

        #########################################################
        self.toolButton_3.clicked.connect(lambda:self.show())
        self.toolButton_2.clicked.connect(lambda:self.show1())
        
        ########################################################
        self.Side_Menu_Num=0

        self.pushButton.clicked.connect(lambda:self.Side_Menu_Def_0())
        self.main_body.mousePressEvent = self.Side_Menu_Def_1
        #########################################################
        self.toolButton_4.clicked.connect(MainWindow.close)
    def show(self):
        self.webView = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.verticalLayout.addWidget(self.webView)
        self.webView.load(QtCore.QUrl("file:///C:/Users/ilyass/Desktop/projet/map%20(1).html"))
        self.webView.setGeometry(QtCore.QRect(190, 80, 600, 500))
        self.verticalLayout.addWidget(self.webView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.addWidget(self.webView)
    def show1(self):
        self.webView = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.verticalLayout.addWidget(self.webView)
        self.webView.load(QtCore.QUrl("file:///C:/Users/ilyass/Downloads/dabab.html"))
        self.webView.setGeometry(QtCore.QRect(190, 80, 600, 500))
        self.verticalLayout.addWidget(self.webView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.addWidget(self.webView)
    def Side_Menu_Def_0(self):
        if self.Side_Menu_Num == 0:
            self.animation1 = QtCore.QPropertyAnimation(self.frame_4, b"maximumWidth")
            self.animation1.setDuration(503)
            self.animation1.setStartValue(50)
            self.animation1.setEndValue(175)
            self.animation1.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
            self.animation1.start()


            self.animation2 = QtCore.QPropertyAnimation(self.frame_4, b"minimumWidth")
            self.animation2.setDuration(503)
            self.animation2.setStartValue(50)
            self.animation2.setEndValue(175)
            self.animation2.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
            self.animation2.start()
            
            self.Side_Menu_Num == 1
        else:
            self.animation1 = QtCore.QPropertyAnimation(self.frame_4, b"maximumWidth")
            self.animation1.setDuration(503)
            self.animation1.setStartValue(175)
            self.animation1.setEndValue(50)
            self.animation1.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
            self.animation1.start()


            self.animation2 = QtCore.QPropertyAnimation(self.frame_4, b"minimumWidth")
            self.animation2.setDuration(503)
            self.animation2.setStartValue(175)
            self.animation2.setEndValue(50)
            self.animation2.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
            self.animation2.start()
            
            self.Side_Menu_Num == 0
    def Side_Menu_Def_1(self, Event):
        if Event.button() == QtCore.Qt.LeftButton:
            
            self.animation1 = QtCore.QPropertyAnimation(self.frame_4, b"maximumWidth")
            self.animation1.setDuration(503)
            self.animation1.setStartValue(175)
            self.animation1.setEndValue(50)
            self.animation1.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
            self.animation1.start()


            self.animation2 = QtCore.QPropertyAnimation(self.frame_4, b"minimumWidth")
            self.animation2.setDuration(503)
            self.animation2.setStartValue(175)
            self.animation2.setEndValue(50)
            self.animation2.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
            self.animation2.start()

            self.Side_Menu_Num == 0
    #######################################################################
    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SHELL"))
        self.toolButton.setText(_translate("MainWindow", "      Stations"))
        self.toolButton_2.setText(_translate("MainWindow", "       Shortest"))
        self.toolButton_3.setText(_translate("MainWindow", "        Map"))
        self.toolButton_4.setText(_translate("MainWindow", "        Log-Out"))

    #def show(self):
        #self.main_body.setText(show_map())
        


 #'''   def show_map(self):
        # name of folder where the html, css, js, image files are located
  #      eel.init('.')

   #     @eel.expose
    #    def bmi_calculator(height,weight):
     #       print(height,weight)

        # 1000 is width of window and 600 is the height
      #  eel.start('map.html', size=(1000,2000))
        



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = MainWindow_Ui()
    ui.setupUi(MainWindow)
    MainWindow.setFixedWidth(824)
    MainWindow.setFixedHeight(593)
    MainWindow.show()
    sys.exit(app.exec_())
